### PR TITLE
Try and be clearer about how official we mean

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by per1234** [comment]
Hi @peternewman. Thanks for your PR. I think it's a reasonable change to make, but I'd like to try to understand the motivation. 

This concept of "official" is used other places like the Arduino project specifications and the Arduino Lint output and documentation, so if I can understand exactly what is unclear about it, I can use that to try to write better documentation related to this subject.

What was your first impression of what the previous sentence meant?

> Run the checks that only apply to official Arduino projects.

**Comment by peternewman** [comment]
> This concept of "official" is used other places like the Arduino project specifications and the Arduino Lint output and documentation, so if I can understand exactly what is unclear about it, I can use that to try to write better documentation related to this subject.

I guess it feels like there are three (or maybe four) levels of libraries:

1. Those which come by default with the Arduino IDE
2. Those listed in the library manager
3. ZIP libraries

I don't know if there are "official" Arduino libraries that don't ship in the default IDE?

For example there are two identically named Teensy libraries to do DMX and RDM:
https://github.com/chrisstaite/TeensyDmx
https://github.com/ssilverman/TeensyDMX

Which behave very differently, the latter (and later) one is "registered", the former (and earlier) isn't. Is one of those therefore official and one not? i.e. does showing up in the IDE make you official?

> What was your first impression of what the previous sentence meant?
> 
> > Run the checks that only apply to official Arduino projects.

Particularly with regards to checks, would every library in the library manager need to pass the checks to be official and in the manager, compare a deb you build and run locally or internally in a company to one that is uploaded to Debian, the latter will have to pass most/all of lintian, it's less important for the former.

Third party seemed a fairly simple way of making that distinction, but perhaps there is a better wording still?

**Comment by per1234** [comment]
>I guess it feels like there are three (or maybe four) levels of libraries:

For Arduino Lint's purposes, there are only two categories:

- "official" - software projects under the Arduino company's ownership. i.e., hosted under the `arduino`, `arduino-libraries`, `bcmi-labs`, or `vidor-libraries` GitHub organizations (definitive list [here](https://github.com/arduino/library-registry-submission-parser/blob/1.0.0/main.go#L51)).
- everything else

Is the meaning of "official" clear from that explanation?

>I don't know if there are "official" Arduino libraries that don't ship in the default IDE?

Yes. Over 100 of them, and more being created all the time! The 18 libraries shipped with the classic Arduino IDE installation are either the very fundamental ones the beginners are most likely to use (e.g., Servo) so they can get straight to having fun after installing the IDE, or ones that were created long ago, before the superior distribution system of Arduino Library Manager was created.

You can find most (with additional scattered through the other organizations I mentioned) of them here:
https://github.com/arduino-libraries
(by the way, we are using `codespell-project/actions-codespell` on pretty much all of them!)

In fact, there are even a couple of 3rd party libraries bundled with the classic Arduino IDE installation: "Adafruit_CircuitPlayground" and "Firmata".

**Comment by peternewman** [comment]
> > I guess it feels like there are three (or maybe four) levels of libraries:
> 
> For Arduino Lint's purposes, there are only two categories:
> 
>     * "official" - software projects under the Arduino company's ownership. i.e., hosted under the `arduino`, `arduino-libraries`, `bcmi-labs`, or `vidor-libraries` GitHub organizations (definitive list [here](https://github.com/arduino/library-registry-submission-parser/blob/1.0.0/main.go#L51)).
> 
>     * everything else
> 
> 
> Is the meaning of "official" clear from that explanation?

Yes, although I'm not sure how best you distil that into something succinct, maybe 3rd party does the trick, as it even covers Firmata mentioned below despite the fact it's in the IDE. Or perhaps the above is as simple as you can make it.

> (by the way, we are using `codespell-project/actions-codespell` on pretty much all of them!)

:heart: 

> In fact, there are even a couple of 3rd party libraries bundled with the classic Arduino IDE installation: "Adafruit_CircuitPlayground" and "Firmata".

Yeah that's the sort of thing that has the potential to cause confusion IMHO with a word such as "official".

**Review by per1234 — APPROVED** [review]

**Pull request merged**
